# Generated by Django 5.2.8 on 2025-11-18 17:11

import django.db.models.deletion
from dateutil.relativedelta import relativedelta
from django.db import migrations, models
from datetime import datetime
import pytz

def create_initial_data(apps, schema_editor):
    # Создаем студентов (email уникальные)
    Student = apps.get_model('lessons', 'Student')
    student1 = Student.objects.create(
        name="Иванов Иван",
        email="ivanov@gmail.com"
    )
    student2 = Student.objects.create(
        name="Петров Петр",
        email="petrov@gmail.com"
    )
    student3 = Student.objects.create(
        name="Павлов Павел",
        email="pavlov@gmail.com"
    )

    # Создаем уроки (указываем время в московском часовом поясе)
    Lesson = apps.get_model('lessons', 'Lesson')
    tz = pytz.timezone('Europe/Moscow')
    ct = datetime.now(tz)
    lesson1 = Lesson.objects.create(
        name="Английский язык",
        teacher="Мария Захаровна",
        start_time=ct + relativedelta(minutes=10),
        end_time=ct + relativedelta(minutes=50)
    )

    # Привязываем учеников к одному уроку
    StudentsLesson = apps.get_model('lessons', 'StudentsLesson')
    StudentsLesson.objects.create(
        lesson=lesson1,
        student=student1
    )
    StudentsLesson.objects.create(
        lesson=lesson1,
        student=student2
    )
    StudentsLesson.objects.create(
        lesson=lesson1,
        student=student3
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название урока')),
                ('teacher', models.CharField(max_length=100, verbose_name='Преподаватель')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя студента')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.student', verbose_name='Студент')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(through='lessons.StudentsLesson', to='lessons.student', verbose_name='Студенты'),
        ),
        migrations.RunPython(create_initial_data),
    ]
